from typing import Dict, Any, List

def generate_readme_template(project_name: str, languages: List[str], entry_points: List[str]) -> str:
    """Generates a professional README markdown scaffold."""
    lang_str = ", ".join(languages) if languages else "Python"
    entry = entry_points[0] if entry_points else "main.py"
    
    return f"""# {project_name or 'Project Name'}

A modern software application built with {lang_str}.

## 🚀 Overview
Explain what this project does, its core value proposition, and key features.

## 🛠️ Prerequisites
- Python 3.10+ (or relevant runtime)
- Git

## 📦 Installation
```bash
# Clone the repository
git clone <repository-url>
cd <repository-folder>

# Install dependencies
pip install -r requirements.txt
```

## ⚡ Quickstart / Usage
Run the application using:
```bash
python {entry}
```

## 🧪 Running Tests
```bash
pytest tests/ -v
```

## 🔒 Configuration & Environment Variables
Create a `.env` file based on `.env.example`:
```bash
cp .env.example .env
```
Populate the required environment variables:
- `API_KEY`: Your API key
- `PORT`: Server port (default: 8000)

## 📄 License
This project is licensed under the MIT License - see the LICENSE file for details.
"""

def generate_test_template(module_name: str = "app") -> str:
    """Generates pytest boilerplate."""
    return f'''import pytest

# Example unit test scaffold generated by ShipSafe
def test_sample_assertion():
    """Verify standard logic and initialization."""
    assert 1 + 1 == 2

def test_environment_configuration():
    """Verify configuration parameters."""
    import os
    # Ensure secrets are loaded from environment
    assert os.getenv("ENV", "development") in ["development", "staging", "production"]
'''

def generate_env_refactor_snippet(var_name: str = "API_KEY", secret_val: str = "your_secret") -> str:
    """Generates os.getenv / dotenv refactor snippet."""
    return f'''# ❌ BEFORE (Insecure Hardcoded Value):
# {var_name} = "{secret_val}"

# ✅ AFTER (Secure Environment Variable Access):
import os
from dotenv import load_dotenv

load_dotenv()

{var_name} = os.getenv("{var_name}")
if not {var_name}:
    raise ValueError("Missing required environment variable: {var_name}")
'''

def generate_gitignore_template() -> str:
    """Generates standard .gitignore template."""
    return """# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
.venv/
env/
ENV/

# Secrets & Environment variables
.env
.env.local
.env.*.local
*.pem
*.key

# IDE & Editor caches
.idea/
.vscode/
*.swp
*.swo

# Testing & Coverage
.pytest_cache/
.coverage
htmlcov/
"""
